# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: gMorpho
networks:
- id: 8453
  start_block: 15330380
  contracts:
  - name: MetaMorpho
    address:
    - 0xc1256Ae5FF1cf2719D4937adb3bbCCab2E00A2Ca
    - 0xc0c5689e6f4D256E861F65465b691aeEcC0dEb12
    handler: src/EventHandlers.ts
    events:
    - event: AccrueInterest(uint256 newTotalAssets, uint256 feeShares)
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: EIP712DomainChanged()
    - event: OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: ReallocateSupply(address indexed caller, bytes32 indexed id, uint256 suppliedAssets, uint256 suppliedShares)
    - event: ReallocateWithdraw(address indexed caller, bytes32 indexed id, uint256 withdrawnAssets, uint256 withdrawnShares)
    - event: RevokePendingCap(address indexed caller, bytes32 indexed id)
    - event: RevokePendingGuardian(address indexed caller)
    - event: RevokePendingMarketRemoval(address indexed caller, bytes32 indexed id)
    - event: RevokePendingTimelock(address indexed caller)
    - event: SetCap(address indexed caller, bytes32 indexed id, uint256 cap)
    - event: SetCurator(address indexed newCurator)
    - event: SetFee(address indexed caller, uint256 newFee)
    - event: SetFeeRecipient(address indexed newFeeRecipient)
    - event: SetGuardian(address indexed caller, address indexed guardian)
    - event: SetIsAllocator(address indexed allocator, bool isAllocator)
    - event: SetSkimRecipient(address indexed newSkimRecipient)
    - event: SetSupplyQueue(address indexed caller, bytes32[] newSupplyQueue)
    - event: SetTimelock(address indexed caller, uint256 newTimelock)
    - event: SetWithdrawQueue(address indexed caller, bytes32[] newWithdrawQueue)
    - event: Skim(address indexed caller, address indexed token, uint256 amount)
    - event: SubmitCap(address indexed caller, bytes32 indexed id, uint256 cap)
    - event: SubmitGuardian(address indexed newGuardian)
    - event: SubmitMarketRemoval(address indexed caller, bytes32 indexed id)
    - event: SubmitTimelock(uint256 newTimelock)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: UpdateLastTotalAssets(uint256 updatedTotalAssets)
    - event: Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)
rollback_on_reorg: false
